name: Uruchom codzienny skrypt

on:
  schedule:
    - cron: '37 18 * * *'  # UTC = 8:00 czasu polskiego (w lecie)
  workflow_dispatch:  # pozwala też odpalać ręcznie

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Zainstaluj Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Uruchom skrypt
      run: python main.py
